USE [master]
GO

/****** Object:  Database [nwr_crdb]    Script Date: 15/10/2025 10:20:07 ******/
CREATE DATABASE [nwr_crdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nwr_crdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CONTRACTTEST\MSSQL\DATA\nwr_crdb.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'nwr_crdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CONTRACTTEST\MSSQL\DATA\nwr_crdb_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [nwr_crdb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nwr_crdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nwr_crdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nwr_crdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nwr_crdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nwr_crdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nwr_crdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [nwr_crdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nwr_crdb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [nwr_crdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nwr_crdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nwr_crdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nwr_crdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nwr_crdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nwr_crdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nwr_crdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nwr_crdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nwr_crdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [nwr_crdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nwr_crdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nwr_crdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nwr_crdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nwr_crdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nwr_crdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nwr_crdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nwr_crdb] SET RECOVERY FULL 
GO

ALTER DATABASE [nwr_crdb] SET  MULTI_USER 
GO

ALTER DATABASE [nwr_crdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nwr_crdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nwr_crdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nwr_crdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [nwr_crdb] SET  READ_WRITE 
GO

